Holdem/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using CommonCardLibrary;
using CommonCardLibrary.Entities;
using Glimpse.Mvc.Message;
using Holdem.Models;
using Holdem.Services;
using Holdem.Utilities;
using Newtonsoft.Json;
using WebGrease.Css.Extensions;

namespace Holdem.Controllers
{
    [Authorize]
    public class TablesController : Controller
    {
        private GameContext db = new GameContext();

        private readonly ITableService _service;
        public TablesController(ITableService service)
        {
            _service = service;
        }
        // GET: Tables
        public ActionResult Index()
        {
            return View(db.Tables.ToList());
        }

        // GET: Tables/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Tables.Find(id);
            if (table == null)
            {
                return HttpNotFound("No table exists for the id");
            }
            var round = db.Rounds.FirstOrDefault(x => x.TableId == table.Id && (!x.Started || x.Active));
            if (round == null)
            {
                return HttpNotFound("No rounds exist, try deleting the table");
            }
            var vm = SetupTableRoundViewModel(round, table);
            return View(vm);
        }

        private TableRoundViewModel SetupTableRoundViewModel(Round round, Table table)
        {
            var players = db.PlayerHands.Include(x => x.Player).Where(x => x.RoundId == round.Id).ToList().AsSafeReadOnly();
            var takenIds = players.Select(x => x.PlayerId);
            var availablePlayers = db.Players.Where(x => x.Cash > table.BuyIn && !takenIds.Contains(x.Id)).ToList().AsSafeReadOnly();
            var vm = new TableRoundViewModel
            {
                Table = table,
                Round = round,
                Players = players,
                AvailablePlayers = availablePlayers
            };
            return vm;
        }

        [HttpPost]
        public ActionResult AddPlayerToTable(AddPlayerViewModel addPlayer)
        {
            string httpNotFound = null;
            var vm = AddSelfToTable(addPlayer, out httpNotFound);
            if (vm == null && httpNotFound != null)
                return HttpNotFound(httpNotFound);
            return PartialView("GamePlayers", vm);
        }

        private TableRoundViewModel AddSelfToTable(AddPlayerViewModel addPlayer,
            out string httpNotFound, bool skipExtra = false)
        {
            var table = db.Tables.Find(addPlayer.TableId);
            if (table == null)
            {
                httpNotFound = "No table exists for the id";
                return null;
            }
            var round =
                 db.Rounds.Include(x => x.Players)
                     .FirstOrDefault(x => x.Id == addPlayer.RoundId && x.Players.Count < Constants.MAX_PLAYERS);
            if (round == null || round.Id == Guid.Empty)
            {
                httpNotFound = "Either the round doesn't exist, or the table is already full. Try another table.";
                return null;
            }
            var player = db.Players.Find(addPlayer.PlayerId);
            if (player == null)
            {
                httpNotFound = "Player does not exist";
                return null;
            }
            if (db.PlayerHands.Find(addPlayer.PlayerId, addPlayer.RoundId) != null)
            {
                httpNotFound = "Player is already a part of the game";
                return null;
            }
            if (player.Cash < table.BuyIn)
            {
                httpNotFound = "Sorry you can't afford the game, go reup";
                return null;
            }
            player.Cash -= table.BuyIn;
            db.PlayerHands.Add(new PlayerHand
            {
                PlayerId = player.Id,
                RoundId = round.Id,
                TotalCash = table.BuyIn,
                Acting = false,
                Active = true,
                Won = false,
                Waiting = skipExtra
            });
            db.SaveChanges();
            httpNotFound = null;
            return skipExtra ? null : SetupTableRoundViewModel(round, table);
        }

        [HttpGet]
        public ActionResult Current(Guid tableId, Guid roundId)
        {

            return Current(new SubmitCardScreenViewModel { TableId = tableId, RoundId = roundId, PlayerId = Guid.Empty, Command = "Null", RaiseAmount = (decimal)0.00 });
        }

        [HttpPost]
        public ActionResult Current(SubmitCardScreenViewModel submission)
        {

            if (submission.Command == "NewEntry") //New person coming to the table need to check in and
                                                  //get put in the table for all of the other things
            {
                string httpNotFound = null;
                var vm = AddSelfToTable(submission, out httpNotFound, true);
                if (httpNotFound != null)
                {
                    ViewBag.NotificationMessage = httpNotFound;
                }
            }

            var table = db.Tables.Find(submission.TableId);
            if (table == null)
                return HttpNotFound("No table exists for the id");
            var round = db.Rounds.Find(submission.RoundId);
            if (round == null)
                return HttpNotFound("The round doesn't exist");
            var playerHands =
                db.PlayerHands.Include(x => x.Player)
                    .Where(x => x.RoundId == submission.RoundId).ToList();

            var playerVms = new List<PlayerViewModel>();
            foreach (var player in playerHands)
                playerVms.Add(new PlayerViewModel(player, player.Player.Name));

            if (playerHands.Count < 3)
                ViewBag.NotificationMessage = "We can't start until we have at least three people";
            var tableVm = new TableViewModel(playerVms, round) { MinBet = table.MinBet };
          

            
            if (!round.Started|| string.IsNullOrEmpty(round.Cards))
            {
                tableVm.CurrentBet = table.MinBet;
                byte count = 1;
                foreach (var player in tableVm.Players)
                    player.Position = count++;
                round.CurrentBet = tableVm.CurrentBet;
                round.Active = true;
                round.Started = true;
                round.Cards = JsonConvert.SerializeObject(tableVm.Cards);
                round.Place = TableRound.PreFlop;
                round.Dealer = tableVm.Dealer;
                InitializePlayers(round.Id, tableVm);
            }
            else if (submission.PlayerId != Guid.Empty && submission.Command != "Null")
            {
                //premptively bringing people to the page that belong
                if (!string.IsNullOrEmpty(ViewBag.NotificationMessage))
                    return View("Current", tableVm);
                var tempPlace = round.Place == TableRound.PreFlop ? (byte)round.Place + 1 : (byte)round.Place * 2;
                tableVm.Place = (TableRound)tempPlace;
                round.Place = tableVm.Place;
                if (submission.Command == "Raise")
                {
                    tableVm.CurrentBet += submission.RaiseAmount;
                    round.CurrentBet = tableVm.CurrentBet;
                }
                tableVm.DetermineWinner();
                if (round.Place == TableRound.End)
                {
                    var nextRound = Guid.NewGuid();
                    db.Rounds.Add(new Round
                    {
                        TableId = table.Id,
                        Dealer = tableVm.Dealer,
                        Id = nextRound,
                        Active = true
                    });
                    foreach (var player in tableVm.Players)
                    {
                        db.PlayerHands.Add(new PlayerHand
                        {
                            TotalCash = player.TotalCash,
                            PlayerId = player.Id,
                            RoundId = nextRound
                        });
                    }
                    db.SaveChanges();
                    return
                        Current(new SubmitCardScreenViewModel()
                        {
                            TableId = submission.TableId,
                            RoundId = nextRound,
                            PlayerId = Guid.Empty,
                            Command = "Null",
                            RaiseAmount = (decimal)0.00
                        });
                }

              
            }
            db.SaveChanges();
            return View(tableVm);
        }

        private void InitializePlayers(Guid roundId, TableViewModel tableVm)
        {
            //See if we have an acting player if we do, let's move to the next
            //player. Ensuring that we don't go over the limit we have of players
            var currentActing = tableVm.Players.Find(x => x.Acting)?.Position;
            if (currentActing == null || currentActing >= tableVm.Players.Count)
                currentActing = 1;
            currentActing++;
            tableVm.DetermineWinner();
            foreach (var player in tableVm.Players)
            {
                player.Waiting = false;
                var playerEntity = db.PlayerHands.Find(player.Id, roundId);
                playerEntity.Cards = JsonConvert.SerializeObject(player.Cards);
                playerEntity.Position = player.Position;
                playerEntity.Won = player.Won;
                playerEntity.Acting = false;

Holdem/Views/Tables/Create.cshtml
@model CommonCardLibrary.Entities.Table

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Table</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinBet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinBet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinBet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxBet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxBet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxBet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuyIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuyIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuyIn, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Holdem/Views/Tables/Current.cshtml
@model CommonCardLibrary.TableViewModel



@using (Html.BeginForm())
{
    <div></div>
    @Html.AntiForgeryToken()
    if (!string.IsNullOrEmpty(@ViewBag.NotificationMessage))
    {
        <div class="alert alert-info" role="alert">@ViewBag.NotificationMessage</div>
    }
   
         @Html.Partial("CurrentTable", Model)
         
   
}
@section scripts
{
    <script type="text/javascript">
        @if (Model!= null && Model.Players.Count > 4)
        {
            @:$(".card").height(105).width(125);
                    @:$(".current-hand").attr("style", "top:87px");
                    @:$(".board").attr("style", "margin-top:155px; margin-bottom:20px;")
                    @:$(".card-container:last").attr("style", "margin-bottom:140px");
                }

    </script>

}

Holdem/Views/Tables/CurrentTable.cshtml
@using CommonCardLibrary
@model CommonCardLibrary.TableViewModel

<h2>Current Bet : @Model.Pot</h2>
<div class="form-horizontal" style="position:relative">
    <h4>Table</h4>
    <hr />
    <div class="btn-group btn-group-lg col-md-4 col-md-offset-4" style="position: absolute; top: -50px" role="group">
        <input type="hidden" name="raiseAmount" value="@Model.MinBet"/>
        <input type="hidden" name="tableId" value="@Model.Id"/>
        <input type="hidden" name="roundId" value="@Model.RoundId"/>
        @*<input type="hidden" name="playerId" value="@Model.PlayerId"/>*@
        <button type="submit" class="btn btn-default" name="Command" value="Raise">Raise</button>
        @if (Model.CurrentBet > (decimal) 0.00)
        {
            <button type="submit" class="btn btn-default" name="Command" value="Call">Call</button>
            <button type="submit" class="btn btn-default" name="Command" value="Fold">Fold</button>
        }
        else
        {
            <button type="submit" class="btn btn-default" name="Command" value="Check">Check</button>
        }
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @Html.Partial("CardGroup", Model, new ViewDataDictionary { { "startingValue", 0 }, { "endingValue", 4 } })
    <div class="row board">
        <div class="col-xs-2">
            <img class="card" src="@Url.Content("~/Content/Images/back.png")" />
        </div>
      
            @foreach (var card in Model.DisplayCards)
            {
                <div class="col-xs-2">
                    @Html.Partial("Card", card)
                </div>
                
            }
        <ul><li>Pot: @Model.Pot</li> <li>CUrrent Bet: @Model.CurrentBet</li></ul>
        <ul><li>Dealer: @Model.GetDealersName()</li> <li>Current Turn: @Model.Place</li></ul>
        
    </div>
    @if (Model.Players.Count > 4)
    {
        @Html.Partial("CardGroup", Model, new ViewDataDictionary { { "startingValue", 4 }, { "endingValue", Model.Players.Count } })
    }
</div>

Holdem/Views/Tables/Delete.cshtml
@model CommonCardLibrary.Entities.Table

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Table</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinBet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinBet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxBet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxBet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BuyIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuyIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Holdem/Views/Tables/Details.cshtml
@model Holdem.Models.TableRoundViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Table</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Table.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Table.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Table.MinBet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Table.MinBet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Table.MaxBet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Table.MaxBet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Table.BuyIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Table.BuyIn)
        </dd>

    </dl>
</div>

@if (Model.Round.Started)
{
    <h2>Round is already in progress</h2>
}

    <div id="CurrentGamePlayers">
        @Html.Partial("GamePlayers", Model)
    </div>






@section scripts
{
    <script>
        var addPlayerToTable = function (submission) {
            $.post("../Current", submission);
        }
    </script>
}

Holdem/Views/Tables/Edit.cshtml
@model CommonCardLibrary.Entities.Table

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Table</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinBet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinBet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinBet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxBet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxBet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxBet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuyIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuyIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuyIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Holdem/Views/Tables/GamePlayers.cshtml
@using Microsoft.AspNet.Identity
@using Constants = Holdem.Utilities.Constants
@model Holdem.Models.TableRoundViewModel

<h2>Current Players</h2>
<hr />
<table>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Cash Left
            </th>
            <th>
                Cash In Game
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var player in Model.Players)
        {
            <tr>
                <td>@player.Player.Name</td>
                <td>@player.Player.Cash</td>
                <td>@player.TotalCash</td>
                <td></td>
            </tr>
        }
    </tbody>
</table>
<br />

<hr />

<span>

    @*@if (Model.Players.Count > 2 && !Model.Round.Started)
        {
            @Html.ActionLink("View Game", "Current", new { tableId = @Model.Table.Id, roundId = @Model.Round.Id })
            <span>  |  </span>
        }*@


    @using (Html.BeginForm("Current", "Tables", FormMethod.Post))
    {
        <input type="hidden" name="tableId" value="@Model.Table.Id" />
            <input type="hidden" name="roundId" value="@Model.Round.Id" />
            <input type="hidden" name="playerId" value="@Guid.Parse(User.Identity.GetUserId())" />
            <input type="hidden" name="command" value="NewEntry" />
            <input type="hidden" name="raiseAmount" value="0.00" />
            if (Model.Players.Count < Constants.MAX_PLAYERS)
            {
                <button type="submit" class="btn btn-link">Take Seat</button>
                <span>|  </span>
            }
            @Html.ActionLink("Back to List", "Index")
    }
</span>

Holdem/Views/Tables/Index.cshtml
@model IEnumerable<CommonCardLibrary.Entities.Table>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MinBet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxBet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BuyIn)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MinBet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaxBet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BuyIn)
        </td>
        
        <td>
          
            @Html.ActionLink("Details", "Details", new { id=item.Id }) 
          
        </td>
    </tr>
}

</table>