Holdem/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CommonCardLibrary.Entities;
using Holdem.Models;
using Holdem.Services;
using Microsoft.AspNet.Identity;

namespace Holdem.Controllers
{
    [Authorize]
    public class PlayersController : Controller
    {
        private GameContext db = new GameContext();

        // GET: Players
        public ActionResult Index()
        {
            var id = Guid.Parse(User.Identity.GetUserId());
            var player = db.Players.Find(id);
            var vm = new DisplayPlayerOnIndexViewModel
            {
                Players = db.Players.ToList(),
                Player = player
            };
 
            return View(vm);
        }

        // GET: Players/Details/5
        public ActionResult Details()
        {
            var id = Guid.Parse(User.Identity.GetUserId());
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }
       

       

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Player player)
        {
            var id = Guid.Parse(User.Identity.GetUserId());
            if (player.Cash > 0)
            {
                db.Players.Find(id).Cash = player.Cash;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Holdem/Views/Players/Create.cshtml
@model CommonCardLibrary.Entities.Player

@{
    ViewBag.Title = "Create";
}

<h2>Create Player</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Player</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cash, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Holdem/Views/Players/Details.cshtml
@model CommonCardLibrary.Entities.Player

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cash)
        </dd>

    </dl>
</div>
<p>
  
    @Html.ActionLink("Back to List", "Index")
</p>

Holdem/Views/Players/Edit.cshtml
@model CommonCardLibrary.Entities.Player

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

Holdem/Views/Players/Index.cshtml
@model Holdem.Models.DisplayPlayerOnIndexViewModel

@{
    ViewBag.Title = "Index";
}


@using (Html.BeginForm("Edit", "Players", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Model.Player.Name </h4><h5>Current Balance</h5>
        <div class="row">
            <div class="col-md-4">
                <input class="form-control text-box single-line valid" data-val="true" data-val-number="The field Cash must be a number." data-val-required="The Cash field is required." id="Player_Cash" name="Cash" type="text" value="@Model.Player.Cash" aria-required="true" aria-invalid="false" aria-describedby="Player_Cash-error">
              
                @Html.ValidationMessageFor(model => model.Player.Cash, "", new {@class = "text-danger"})
            </div>
            <div class="col-md-4">
                @Html.ActionLink("Details", "Details", null, new {@class = "btn btn-default"})
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>

            @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        </div>
        <hr />
        <input type="hidden" name="Id" value="@Model.Player.Id"/>
        <input type="hidden" name="Name" value="@Model.Player.Name"/>
    </div>
}





<h2>Player List</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Player.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Player.Cash)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Players) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cash)
        </td>
        <td>
          
        </td>
    </tr>
}

</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}